import React, { useState } from 'react';
import { HelpCircle, ChevronDown } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
}

export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs: FaqItem[] = [
    {
      question: 'What is calculated deterministically vs generated by an LLM?',
      answer:
        'All bus factors, commit concentration percentages, 6-factor departure risk scores, and 4-factor Jaccard successor matches are computed deterministically in code from your Neo4j graph and PostgreSQL telemetry. The model is used strictly to understand natural language queries and synthesize retrieved graph citations into structured English answers.',
    },
    {
      question: 'Where does our company data live, and is our code kept private?',
      answer:
        'Your code, pull requests, Jira tickets, and Slack messages stay completely inside your private infrastructure. Cortex is self-hosted via Docker or within your AWS, GCP, or Azure VPC. Source code, tokens, and graph entities never leave your cloud perimeter.',
    },
    {
      question: 'Can Cortex run in completely air-gapped environments without internet access?',
      answer:
        'Yes. Cortex natively supports local OpenAI-compatible inference servers including Ollama and vLLM. It can run entirely air-gapped on internal GPU or CPU nodes with zero outbound internet connectivity.',
    },
    {
      question: 'How does Cortex filter out automated bots or mass refactor commits?',
      answer:
        'Our graph ingestion pipeline analyzes author lineage, PR review participation, and cross-tool discussion context. Automated dependency bots (Dependabot, Renovate) and purely synthetic format changes are filtered out so they do not artificially distort bus factor metrics.',
    },
    {
      question: 'Will our engineers feel surveilled or micromanaged?',
      answer:
        'No. Cortex explicitly does not track employee hours, keystroke frequency, or individual productivity metrics. It measures architectural knowledge distribution and single-point-of-failure risks across codebases to protect teams from burnout and sudden key-person turnover.',
    },
    {
      question: 'What permissions does Cortex require on our GitHub or Jira organization?',
      answer:
        'Cortex requires scoped, read-only repository permissions (commits, pull requests, issues) and webhook event subscription. Cortex never writes to your main branch or alters repository settings unless you explicitly trigger an automated documentation PR.',
    },
    {
      question: 'How long does initial historical graph indexing take for large codebases?',
      answer:
        'Real-time webhooks process incrementally in sub-seconds. Initial historical backfill for 20+ active repositories typically finishes in 10 to 20 minutes depending on commit depth and repository scale.',
    },
    {
      question: 'Why is Cortex free for design partners right now?',
      answer:
        'We are an early-stage 2-person engineering team focused on proving quantitative risk reduction in real engineering environments. We prioritize direct product feedback and architecture refinement over premature paywalls. The self-hosted community edition will remain free.',
    },
  ];

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-20 md:py-28 bg-[#0B0F14] relative border-t border-white/10 antialiased">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-md bg-[#12181F] border border-white/10 text-slate-300 text-xs font-mono mb-4">
            <HelpCircle className="w-3.5 h-3.5 text-blue-400" />
            <span>Technical FAQ</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-white tracking-tight font-sans">
            Frequently answered questions for engineering leaders.
          </h2>
          <p className="mt-3 text-sm sm:text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
            Architecture details, data privacy guarantees, and deployment mechanics.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-3">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className="bg-[#12181F] border border-white/10 rounded-xl transition-colors overflow-hidden"
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 cursor-pointer focus:outline-none focus-visible:ring-1 focus-visible:ring-blue-500"
                >
                  <span className="text-sm sm:text-base font-semibold text-white font-sans">
                    {faq.question}
                  </span>
                  <div
                    className={`p-1.5 rounded-lg border transition-transform duration-200 shrink-0 ${
                      isOpen
                        ? 'bg-blue-600/10 border-blue-500/30 text-blue-400 rotate-180'
                        : 'bg-[#0E131A] border-white/10 text-slate-400'
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 pt-1 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-white/5 animate-in fade-in duration-150">
                    <p>{faq.answer}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
