import React, { useState, useMemo } from 'react';
import { HelpCircle, ChevronDown, Search } from 'lucide-react';

interface FaqItem {
  id: string;
  category: 'differentiation' | 'determinism' | 'security';
  categoryLabel: string;
  question: string;
  answer: string;
}

export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const faqs: FaqItem[] = [
    {
      id: 'faq-1',
      category: 'differentiation',
      categoryLabel: 'Vs Copilot & AI Bots',
      question: 'How is Cortex different from GitHub Copilot or OpenAI Codex?',
      answer:
        'GitHub Copilot, Cursor, and Codex are tactical in-editor syntax autocompletion and code generation tools. They operate on the file currently open in a developer\'s IDE, with zero cross-repository organizational context. They do not know who owns which service, what happens if an engineer resigns, which microservices represent critical Single Points of Failure (SPOFs), or what architectural decisions were reached in Slack or Jira six months ago. Cortex operates at the organizational architecture layer: it continuously monitors system continuity, decayed code ownership, and departure risk across your entire engineering organization.'
    },
    {
      id: 'faq-2',
      category: 'differentiation',
      categoryLabel: 'Vs Glean & Search',
      question: 'How is Cortex different from Glean or enterprise search tools?',
      answer:
        'Glean and Coveo are broad horizontal enterprise search tools designed for HR, Sales, and general office documentation (Google Drive, Notion, Confluence wikis). They cost $50k+ per year and search human-written documents. However, software engineers rarely write or maintain documentation, causing wikis to quickly go stale. Glean cannot parse Git commit AST trees, microservice dependencies, or co-authorship trailers. Most importantly, Glean does not compute mathematical bus factors, 180-day ownership decay, or 4-factor successor recommendation scores. Cortex is Git-graph-native and self-hosted inside your VPC.'
    },
    {
      id: 'faq-3',
      category: 'determinism',
      categoryLabel: 'Zero Hallucination',
      question: 'Can I trust the numbers? How do I know the AI isn\'t hallucinating metrics?',
      answer:
        'Zero metrics in Cortex are generated by an LLM. Cortex operates on a strict architectural separation of concerns: a Deterministic Calculator Engine and a Natural Language Formatter. All bus factors, commit sums, lead times, 6-factor departure risk scores, and 4-factor Jaccard successor rankings are calculated directly in pure TypeScript algorithms operating on your PostgreSQL database and Neo4j property graph. The LLM is used strictly to understand natural language questions and format structured graph citations into readable sentences. Furthermore, post-recalculation invariant guards automatically enforce cross-table mathematical parity.'
    },
    {
      id: 'faq-4',
      category: 'determinism',
      categoryLabel: 'Missing Data & Audits',
      question: 'What if Cortex is wrong or data is missing?',
      answer:
        'Every metric, insight, and answer surfaced by Cortex provides an immutable evidence chain: exact commit SHAs, author git trailers, pull request numbers, and linked Slack threads. You can independently verify any calculation by inspecting the underlying Cypher and SQL queries. Furthermore, Cortex implements strict data transparency rules: if a repository has fewer than 5 events, it explicitly flags the metric as "partial" with a small sample-size warning rather than fabricating a plausible estimate. If a repository has 0 commits, it strictly collapses to 0 contributors and status empty.'
    },
    {
      id: 'faq-5',
      category: 'security',
      categoryLabel: 'VPC Sovereignty',
      question: 'Do you store or train models on our proprietary source code?',
      answer:
        'No. Under our BYOC (Bring Your Own Cloud) deployment model, Cortex runs entirely as a self-hosted container inside your private AWS, GCP, Azure, or on-premise VPC. Your proprietary source code never leaves your infrastructure perimeter. We do not clone full repository source code blobs into an external multi-tenant cloud. Ingestion is scoped to read-only metadata (commit diff sizes, authors, PR timestamps). The only outbound calls are compact 1-2 sentence semantic summaries dispatched to enterprise LLM endpoints under zero-data-retention agreements where data cannot be logged or used for model training.'
    },
    {
      id: 'faq-6',
      category: 'security',
      categoryLabel: 'Read-Only Scopes',
      question: 'What permissions does Cortex require on GitHub, Slack, and Jira?',
      answer:
        'Cortex requires strictly scoped, read-only permissions and webhook subscriptions. For GitHub: repository read-only access for commits, pull requests, issues, and discussions. Cortex has zero write permissions to your default branches and cannot push code or alter repository settings. For Slack: read-only access to configured public engineering channels. For Jira: read-only issue ticket metadata.'
    },
    {
      id: 'faq-7',
      category: 'determinism',
      categoryLabel: 'Noise & Bot Filtering',
      question: 'How does Cortex filter out automated bots or mass refactor commits?',
      answer:
        'All ingestion pipelines filter activity through isBotAccount(name, email, username, externalId), matching against KNOWN_BOT_USERNAMES (Dependabot, Renovate, GitHub Actions, Snyk) and heuristic patterns (*[bot], *-bot, *@users.noreply.github.com). Bot commits are excluded from human metrics, bus factors, and successor candidates by default, with an explicit includeBots: true parameter supported on all APIs for full audit transparency.'
    },
    {
      id: 'faq-8',
      category: 'security',
      categoryLabel: 'Anti-Surveillance Ethics',
      question: 'Will our software engineers feel surveilled or micromanaged?',
      answer:
        'No. Cortex adheres to strict anti-productivity ethics. It contains zero keystroke logging, employee active-hour tracking, or individual productivity ranking algorithms. Metrics are explicitly qualified as engineering continuity and architectural knowledge indicators to protect teams from burnout and sudden single-point-of-failure turnover, not performance rankings.'
    }
  ];

  const filteredFaqs = useMemo(() => {
    return faqs.filter(f => {
      const matchesCategory = selectedCategory === 'all' || f.category === selectedCategory;
      const matchesSearch = searchQuery === '' || 
        f.question.toLowerCase().includes(searchQuery.toLowerCase()) || 
        f.answer.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });
  }, [faqs, selectedCategory, searchQuery]);

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-12 md:py-16 bg-[#06090F] relative antialiased">
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-slate-500/20 to-transparent" />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-10">
          <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-slate-500/10 border border-slate-500/20 text-slate-300 text-xs font-mono mb-5">
            <HelpCircle className="w-3.5 h-3.5 text-indigo-400" />
            <span>Technical FAQ &amp; Objections</span>
          </div>

          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white tracking-tight font-sans">
            Frequently answered <span className="gradient-text">technical questions.</span>
          </h2>

          <p className="mt-4 text-sm sm:text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
            Honest answers to the hardest questions about system architecture, mathematical determinism, enterprise privacy, and competitive differentiation.
          </p>
        </div>

        {/* Filter Bar & Quick Search */}
        <div className="space-y-4 mb-10">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-3">
            {/* Category Tabs */}
            <div className="inline-flex p-1 rounded-xl bg-[#0D1117] border border-white/[0.06] text-xs font-mono w-full sm:w-auto overflow-x-auto">
              <button
                onClick={() => setSelectedCategory('all')}
                className={`px-3 py-1.5 rounded-lg cursor-pointer transition-all whitespace-nowrap ${
                  selectedCategory === 'all' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-white'
                }`}
              >
                All (8)
              </button>
              <button
                onClick={() => setSelectedCategory('differentiation')}
                className={`px-3 py-1.5 rounded-lg cursor-pointer transition-all whitespace-nowrap ${
                  selectedCategory === 'differentiation' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-white'
                }`}
              >
                Vs Copilot &amp; Glean
              </button>
              <button
                onClick={() => setSelectedCategory('determinism')}
                className={`px-3 py-1.5 rounded-lg cursor-pointer transition-all whitespace-nowrap ${
                  selectedCategory === 'determinism' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-white'
                }`}
              >
                Determinism &amp; Math
              </button>
              <button
                onClick={() => setSelectedCategory('security')}
                className={`px-3 py-1.5 rounded-lg cursor-pointer transition-all whitespace-nowrap ${
                  selectedCategory === 'security' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-white'
                }`}
              >
                Security &amp; Privacy
              </button>
            </div>

            {/* Search Input */}
            <div className="relative w-full sm:w-64">
              <Search className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search FAQ keywords..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 bg-[#0D1117] border border-white/[0.06] rounded-xl text-xs font-sans text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500 transition-colors"
              />
            </div>
          </div>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-3.5">
          {filteredFaqs.length === 0 ? (
            <div className="p-8 text-center text-slate-400 font-mono text-xs rounded-xl bg-[#0D1117] border border-white/[0.04]">
              No questions found matching "{searchQuery}".
            </div>
          ) : (
            filteredFaqs.map((faq, index) => {
              const isOpen = openIndex === index;
              return (
                <div
                  key={faq.id}
                  className={`bg-[#0D1117] border rounded-2xl transition-all overflow-hidden ${
                    isOpen ? 'border-indigo-500/40 shadow-lg shadow-indigo-500/5' : 'border-white/[0.06] hover:border-white/[0.12]'
                  }`}
                >
                  <button
                    onClick={() => toggleFaq(index)}
                    className="w-full p-5 sm:p-6 text-left flex items-start justify-between gap-4 cursor-pointer focus:outline-none"
                  >
                    <div className="space-y-1.5">
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 text-indigo-300 border border-white/[0.04]">
                        {faq.categoryLabel}
                      </span>
                      <h3 className="text-sm sm:text-base font-semibold text-white font-sans">
                        {faq.question}
                      </h3>
                    </div>

                    <div
                      className={`p-1.5 rounded-lg border transition-transform duration-200 shrink-0 mt-1 ${
                        isOpen
                          ? 'bg-indigo-600/10 border-blue-500/30 text-indigo-400 rotate-180'
                          : 'bg-[#0A0E16] border-white/[0.06] text-slate-400'
                      }`}
                    >
                      <ChevronDown className="w-4 h-4" />
                    </div>
                  </button>

                  {isOpen && (
                    <div className="px-5 sm:px-6 pb-6 pt-1 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-white/[0.04] font-sans">
                      <p>{faq.answer}</p>
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>

      </div>
    </section>
  );
};
