import React from 'react';
import { ShieldCheck, AlertOctagon, Check } from 'lucide-react';

export const GuaranteesSection: React.FC = () => {
  const guarantees = [
    {
      title: 'Zero Generative Guesswork',
      description:
        'Every risk score, bus factor, ownership decay percentage, and successor ranking is generated by deterministic TypeScript algorithms operating directly on your PostgreSQL telemetry and Neo4j property graph. Zero LLM involvement in any numerical calculation.'
    },
    {
      title: 'Single Source of Truth',
      description:
        'The executive dashboard, natural-language chat agent, API endpoints, and scheduled reports query the identical analytical functions in packages/analytics/. UI tooltips, internal documentation, and public definitions never disagree.'
    },
    {
      title: 'Honest Statistical Distributions',
      description:
        'Metrics are presented as medians (p50), 90th percentiles (p90), and interquartile ranges (IQR) rather than distorted scalar averages. Dormant outliers (>30 days) and automated bot accounts are segregated rather than silently buried.'
    },
    {
      title: 'Anti-Productivity Ethics',
      description:
        'Metrics are strictly engineering continuity and knowledge blast-radius indicators. Cortex contains zero employee keystroke monitoring, individual ranking leaderboards, or productivity quotas.'
    },
    {
      title: 'Self-Healing Invariant Integrity',
      description:
        'Post-recalculation invariant guards automatically enforce cross-table mathematical parity. A repository with 0 commits strictly collapses to 0 contributors, null primary owner, and bus factor 0. Active repository bus factors never exceed total contributor counts.'
    }
  ];

  const nonGuarantees = [
    {
      title: 'External Offline & In-Person Discussions',
      description:
        'Cortex cannot capture hallway conversations, whiteboarding sessions, unrecorded telephone calls, or discussions conducted in private repositories without webhook integration.'
    },
    {
      title: 'Syntactic Code Quality & Correctness',
      description:
        'Metric calculations measure organizational knowledge distribution, not syntax correctness, unit test coverage, or runtime efficiency. For code syntax and vulnerabilities, pair Cortex with static analyzers (SAST/linter).'
    },
    {
      title: 'Resignation Intent or Attrition Probability',
      description:
        'Cortex evaluates the architectural blast-radius and system vulnerability if an engineer departs. It does not predict human career decisions, job satisfaction, or personal resignation timelines.'
    },
    {
      title: 'Automated Wiki Replacement',
      description:
        'Cortex surfaces exactly which microservices lack documentation and exposes real commit history. It does not hallucinate unverified architectural documentation or replace human architectural review.'
    }
  ];

  return (
    <section id="guarantees" className="py-20 md:py-28 bg-[#0B0F14] relative border-t border-white/10 antialiased">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-md bg-[#12181F] border border-white/10 text-slate-300 text-xs font-mono mb-4">
            <ShieldCheck className="w-3.5 h-3.5 text-blue-400" />
            <span>Engineering Boundaries &amp; Integrity</span>
          </div>

          <h2 className="text-3xl sm:text-4xl font-bold text-white tracking-tight font-sans">
            What Cortex guarantees. And what it does not.
          </h2>

          <p className="mt-3 text-sm sm:text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
            Honest capability boundaries pulled directly from our engineering audit. We document what the platform mathematically proves, and where human context remains essential.
          </p>
        </div>

        {/* Two-Column Side-by-Side Comparison */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          
          {/* Column 1: What Cortex Guarantees */}
          <div className="bg-[#12181F] border border-blue-500/30 rounded-2xl p-6 sm:p-8 space-y-6">
            <div className="flex items-center space-x-3 pb-4 border-b border-white/10">
              <div className="w-9 h-9 rounded-lg bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400">
                <Check className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white font-sans">
                  What Cortex Guarantees
                </h3>
                <span className="text-xs font-mono text-blue-400">Deterministic Mathematical Proofs</span>
              </div>
            </div>

            <div className="space-y-5">
              {guarantees.map((item, idx) => (
                <div key={idx} className="space-y-1.5">
                  <div className="flex items-center space-x-2 text-sm font-semibold text-white font-sans">
                    <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                    <span>{item.title}</span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed font-sans pl-3.5">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Column 2: What Cortex Does NOT Guarantee */}
          <div className="bg-[#12181F] border border-white/10 rounded-2xl p-6 sm:p-8 space-y-6">
            <div className="flex items-center space-x-3 pb-4 border-b border-white/10">
              <div className="w-9 h-9 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-slate-400">
                <AlertOctagon className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white font-sans">
                  What Cortex Does NOT Guarantee
                </h3>
                <span className="text-xs font-mono text-slate-400">Explicit Product Boundaries</span>
              </div>
            </div>

            <div className="space-y-5">
              {nonGuarantees.map((item, idx) => (
                <div key={idx} className="space-y-1.5">
                  <div className="flex items-center space-x-2 text-sm font-semibold text-slate-200 font-sans">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                    <span>{item.title}</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed font-sans pl-3.5">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </section>
  );
};
