import React, { useEffect, useState } from 'react';
import { getBusFactor, getRepositoryDetails, type RepoMetric, type RepositoryDetails } from '../lib/api';
import { ShieldAlert, AlertTriangle, UserCheck, Code, Layers, RefreshCw, ArrowRight } from 'lucide-react';
import { RepoDetailModal } from '../components/RepoDetailModal';

interface BusFactorPageProps {
  onSyncUpdated?: (date: Date) => void;
}

export const BusFactorPage: React.FC<BusFactorPageProps> = ({ onSyncUpdated }) => {
  const [repos, setRepos] = useState<RepoMetric[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Detail Modal state
  const [selectedRepoDetails, setSelectedRepoDetails] = useState<RepositoryDetails | null>(null);
  const [detailsLoading, setDetailsLoading] = useState<boolean>(false);
  const [detailsError, setDetailsError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);

  const fetchBusFactor = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getBusFactor();
      setRepos(data.repos || []);
      if (onSyncUpdated) {
        onSyncUpdated(new Date());
      }
    } catch (err: any) {
      setError(err.message || 'Failed to fetch Bus Factor data');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenDetails = async (repoName: string) => {
    setIsModalOpen(true);
    setDetailsLoading(true);
    setDetailsError(null);
    setSelectedRepoDetails(null);
    try {
      const details = await getRepositoryDetails(repoName);
      setSelectedRepoDetails(details);
    } catch (err: any) {
      setDetailsError(err.message || `Failed to fetch details for ${repoName}`);
    } finally {
      setDetailsLoading(false);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setSelectedRepoDetails(null);
    setDetailsError(null);
  };

  useEffect(() => {
    fetchBusFactor();
  }, []);

  if (loading) {
    return (
      <div className="p-8 space-y-6 animate-pulse">
        <div className="h-8 w-64 bg-slate-800 rounded-lg"></div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-48 bg-slate-900/80 rounded-xl border border-slate-800"></div>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8">
        <div className="p-6 bg-rose-500/10 border border-rose-500/30 rounded-xl flex items-center justify-between">
          <div className="flex items-center space-x-3 text-rose-300">
            <AlertTriangle className="h-6 w-6 text-rose-400" />
            <div>
              <h4 className="font-semibold text-white">Failed to Load Bus Factor Metrics</h4>
              <p className="text-xs text-rose-300/80">{error}</p>
            </div>
          </div>
          <button
            onClick={() => fetchBusFactor()}
            className="px-4 py-2 bg-rose-500/20 hover:bg-rose-500/30 border border-rose-500/40 text-rose-200 text-xs font-semibold rounded-lg flex items-center space-x-2 transition-all cursor-pointer"
          >
            <RefreshCw className="h-4 w-4" />
            <span>Retry</span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">
      {/* Header Banner */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <ShieldAlert className="h-6 w-6 text-amber-400" />
            <span>Bus Factor & Repository Vulnerability</span>
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            Repositories ranked by single point of failure risk. Click any repository card to inspect maintainers, commit timeline, stack technologies, and suggested backup owners.
          </p>
        </div>
        <button
          onClick={() => fetchBusFactor()}
          className="px-3 py-1.5 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs text-slate-300 hover:text-white rounded-lg flex items-center space-x-2 cursor-pointer transition-all"
        >
          <RefreshCw className="h-3.5 w-3.5" />
          <span>Refresh</span>
        </button>
      </div>

      {/* Empty Cold-Start State */}
      {repos.length === 0 ? (
        <div className="glass-card p-12 text-center space-y-3">
          <Layers className="h-10 w-10 text-slate-500 mx-auto" />
          <h4 className="text-base font-semibold text-slate-300">No Repository Metrics Populated Yet</h4>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Metrics are generated by the nightly cron worker or webhook events. Once repository activities are indexed, bus factor calculations will appear here.
          </p>
        </div>
      ) : (
        /* Repository Cards Grid */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {repos.map(repo => {
            const isEmpty = repo.status === 'empty' || repo.status === 'scaffold' || (Number(repo.bus_factor) === 0 && Number(repo.risk_score) === 0);
            const isHighRisk = !isEmpty && (repo.bus_factor <= 1 || repo.risk_score >= 70);
            return (
              <div
                key={repo.external_id || repo.repo_name}
                role="button"
                tabIndex={0}
                aria-label={`Inspect repository details for ${repo.repo_name}`}
                onClick={() => handleOpenDetails(repo.repo_name)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    handleOpenDetails(repo.repo_name);
                  }
                }}
                className="glass-card glass-card-hover p-6 flex flex-col justify-between space-y-4 cursor-pointer group hover:border-indigo-500/50 hover:shadow-lg hover:shadow-indigo-500/10 transition-all duration-200 focus-visible:ring-2 focus-visible:ring-indigo-500 focus:outline-none"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
                      Bus Factor: <strong className="text-white">{repo.bus_factor !== undefined && repo.bus_factor !== null ? repo.bus_factor : 'N/A'}</strong>
                    </span>
                    <span
                      className={`text-xs font-semibold px-2.5 py-0.5 rounded-full ${
                        isEmpty
                          ? 'bg-slate-800 text-slate-400 border border-slate-700'
                          : isHighRisk
                          ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30'
                          : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                      }`}
                    >
                      {isEmpty ? 'Empty / Scaffold' : `Risk ${repo.risk_score ?? 0}%`}
                    </span>
                  </div>

                  <h4 className="text-lg font-bold text-white mt-3 flex items-center justify-between group-hover:text-indigo-300 transition-colors">
                    <div className="flex items-center space-x-2">
                      <Code className="h-4 w-4 text-indigo-400" />
                      <span>{repo.repo_name}</span>
                    </div>
                    <ArrowRight className="h-4 w-4 text-slate-500 opacity-0 group-hover:opacity-100 group-hover:translate-x-1 transition-all" />
                  </h4>

                  {isEmpty ? (
                    <div className="flex items-center space-x-2 text-xs text-slate-500 mt-2 italic">
                      <Layers className="h-3.5 w-3.5 text-slate-600" />
                      <span>No commits / scaffold repo</span>
                    </div>
                  ) : repo.primary_owner ? (
                    <div className="flex items-center space-x-2 text-xs text-slate-400 mt-2">
                      <UserCheck className="h-3.5 w-3.5 text-amber-400" />
                      <span>Primary: <strong className="text-slate-200 font-medium">{repo.primary_owner}</strong></span>
                    </div>
                  ) : (
                    <div className="flex items-center space-x-2 text-xs text-slate-500 mt-2 italic">
                      <UserCheck className="h-3.5 w-3.5 text-slate-600" />
                      <span>Single maintainer codebase</span>
                    </div>
                  )}
                </div>

                <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
                  <span>Contributors: <strong className="text-slate-200">{repo.contributor_count ?? 0}</strong></span>
                  <span className="text-[11px] font-semibold text-indigo-400 group-hover:underline flex items-center gap-1">
                    <span>Inspect Risk</span>
                    <span>→</span>
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Deep Inspection Detail Modal */}
      {isModalOpen && (
        <RepoDetailModal
          details={selectedRepoDetails}
          loading={detailsLoading}
          error={detailsError}
          onClose={handleCloseModal}
        />
      )}
    </div>
  );
};
