import React, { useEffect, useState } from 'react';
import { getBusFactor, type RepoMetric } from '../lib/api';
import { ShieldAlert, AlertTriangle, UserCheck, Code, Layers, RefreshCw } from 'lucide-react';

export const BusFactorPage: React.FC = () => {
  const [repos, setRepos] = useState<RepoMetric[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  const fetchBusFactor = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getBusFactor();
      setRepos(data.repos || []);
    } catch (err: any) {
      setError(err.message || 'Failed to fetch Bus Factor data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBusFactor();
  }, []);

  if (loading) {
    return (
      <div className="p-8 space-y-6 animate-pulse">
        <div className="h-8 w-64 bg-slate-800 rounded-lg"></div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-48 bg-slate-900/80 rounded-xl border border-slate-800"></div>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8">
        <div className="p-6 bg-rose-500/10 border border-rose-500/30 rounded-xl flex items-center justify-between">
          <div className="flex items-center space-x-3 text-rose-300">
            <AlertTriangle className="h-6 w-6 text-rose-400" />
            <div>
              <h4 className="font-semibold text-white">Failed to Load Bus Factor Metrics</h4>
              <p className="text-xs text-rose-300/80">{error}</p>
            </div>
          </div>
          <button
            onClick={fetchBusFactor}
            className="px-4 py-2 bg-rose-500/20 hover:bg-rose-500/30 border border-rose-500/40 text-rose-200 text-xs font-semibold rounded-lg flex items-center space-x-2 transition-all"
          >
            <RefreshCw className="h-4 w-4" />
            <span>Retry</span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">
      {/* Header Banner */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <ShieldAlert className="h-6 w-6 text-amber-400" />
            <span>Bus Factor & Repository Vulnerability</span>
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            Repositories ordered by lowest Bus Factor (highest single point of failure risk).
          </p>
        </div>
        <button
          onClick={fetchBusFactor}
          className="px-3 py-1.5 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs text-slate-300 hover:text-white rounded-lg flex items-center space-x-2"
        >
          <RefreshCw className="h-3.5 w-3.5" />
          <span>Refresh</span>
        </button>
      </div>

      {/* Empty Cold-Start State */}
      {repos.length === 0 ? (
        <div className="glass-card p-12 text-center space-y-3">
          <Layers className="h-10 w-10 text-slate-500 mx-auto" />
          <h4 className="text-base font-semibold text-slate-300">No Repository Metrics Populated Yet</h4>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Metrics are generated by the nightly cron worker or webhook events. Once repository activities are indexed, bus factor calculations will appear here.
          </p>
        </div>
      ) : (
        /* Repository Cards Grid */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {repos.map(repo => {
            const isHighRisk = repo.bus_factor <= 1 || repo.risk_score >= 70;
            return (
              <div
                key={repo.external_id || repo.repo_name}
                className="glass-card glass-card-hover p-6 flex flex-col justify-between space-y-4"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
                      Bus Factor: <strong className="text-white">{repo.bus_factor ?? 1}</strong>
                    </span>
                    <span
                      className={`text-xs font-semibold px-2.5 py-0.5 rounded-full ${
                        isHighRisk
                          ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30'
                          : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                      }`}
                    >
                      Risk {repo.risk_score ?? 0}%
                    </span>
                  </div>

                  <h4 className="text-lg font-bold text-white mt-3 flex items-center space-x-2">
                    <Code className="h-4 w-4 text-indigo-400" />
                    <span>{repo.repo_name}</span>
                  </h4>

                  {repo.primary_owner && (
                    <div className="flex items-center space-x-2 text-xs text-slate-400 mt-2">
                      <UserCheck className="h-3.5 w-3.5 text-amber-400" />
                      <span>Primary Owner: <strong className="text-slate-200 font-medium">{repo.primary_owner}</strong></span>
                    </div>
                  )}
                </div>

                <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
                  <span>Contributors: <strong className="text-slate-200">{repo.contributor_count ?? 1}</strong></span>
                  <span className="text-[10px] text-slate-500">
                    {repo.computed_at ? new Date(repo.computed_at).toLocaleDateString() : 'Recent'}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
